//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoArtCouro.Resource.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Erros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Erros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoArtCouro.Resource.Resources.Erros", typeof(Erros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome duplicado, já existe um grupo com esse nome.
        /// </summary>
        public static string DuplicateGruopName {
            get {
                return ResourceManager.GetString("DuplicateGruopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome duplicado, já existe um usuário com esse nome.
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço vazio.
        /// </summary>
        public static string EmptyAddress {
            get {
                return ResourceManager.GetString("EmptyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF vazio.
        /// </summary>
        public static string EmptyCPF {
            get {
                return ResourceManager.GetString("EmptyCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do grupo vazio.
        /// </summary>
        public static string EmptyGroupName {
            get {
                return ResourceManager.GetString("EmptyGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado civil vazio.
        /// </summary>
        public static string EmptyMaritalStatus {
            get {
                return ResourceManager.GetString("EmptyMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametros vazios.
        /// </summary>
        public static string EmptyParameters {
            get {
                return ResourceManager.GetString("EmptyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa vazia.
        /// </summary>
        public static string EmptyPerson {
            get {
                return ResourceManager.GetString("EmptyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG vazio.
        /// </summary>
        public static string EmptyRG {
            get {
                return ResourceManager.GetString("EmptyRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo vazio.
        /// </summary>
        public static string EmptySex {
            get {
                return ResourceManager.GetString("EmptySex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido.
        /// </summary>
        public static string InvalidCNPJ {
            get {
                return ResourceManager.GetString("InvalidCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido.
        /// </summary>
        public static string InvalidCPF {
            get {
                return ResourceManager.GetString("InvalidCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credencial inválida.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do usuário inválido.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome ou senhas estão incorretos.
        /// </summary>
        public static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida.
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meio de comunicação vazio.
        /// </summary>
        public static string MeansOfCommunicationEmpty {
            get {
                return ResourceManager.GetString("MeansOfCommunicationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há grupo para o filtro informado.
        /// </summary>
        public static string NoGruopForTheGivenFilter {
            get {
                return ResourceManager.GetString("NoGruopForTheGivenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há usuarios para o filtro informado.
        /// </summary>
        public static string NoUsersForTheGivenFilter {
            get {
                return ResourceManager.GetString("NoUsersForTheGivenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papel pessoa vazio.
        /// </summary>
        public static string PaperEmptyPerson {
            get {
                return ResourceManager.GetString("PaperEmptyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissões não cadastradas.
        /// </summary>
        public static string PermissionsNotRegistered {
            get {
                return ResourceManager.GetString("PermissionsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Obrigatório.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
    }
}
