//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoArtCouro.Resource.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoArtCouro.Resource.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contas a Pagar.
        /// </summary>
        public static string AccountsPayable {
            get {
                return ResourceManager.GetString("AccountsPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contas a Receber.
        /// </summary>
        public static string AccountsReceivable {
            get {
                return ResourceManager.GetString("AccountsReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Produto.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contas a Pagar.
        /// </summary>
        public static string BillsToPay {
            get {
                return ResourceManager.GetString("BillsToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contas a receber.
        /// </summary>
        public static string BillsToReceive {
            get {
                return ResourceManager.GetString("BillsToReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celulares.
        /// </summary>
        public static string CellPhones {
            get {
                return ResourceManager.GetString("CellPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string CEP {
            get {
                return ResourceManager.GetString("CEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Cliente.
        /// </summary>
        public static string ClientCode {
            get {
                return ResourceManager.GetString("ClientCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Cliente.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        public static string CNPJ {
            get {
                return ResourceManager.GetString("CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Compra.
        /// </summary>
        public static string CodeBuy {
            get {
                return ResourceManager.GetString("CodeBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão social.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string Complement {
            get {
                return ResourceManager.GetString("Complement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condições de Pagamentos.
        /// </summary>
        public static string ConditionsPayments {
            get {
                return ResourceManager.GetString("ConditionsPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF/CNPJ.
        /// </summary>
        public static string CPFCNPJ {
            get {
                return ResourceManager.GetString("CPFCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Vencimento.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Compra.
        /// </summary>
        public static string EditBuy {
            get {
                return ResourceManager.GetString("EditBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar cliente.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar funcionário.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar fornecedor.
        /// </summary>
        public static string EditProvider {
            get {
                return ResourceManager.GetString("EditProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Venda.
        /// </summary>
        public static string EditSale {
            get {
                return ResourceManager.GetString("EditSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Funcionário.
        /// </summary>
        public static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionários.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido.
        /// </summary>
        public static string ERR_CPF {
            get {
                return ResourceManager.GetString("ERR_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        public static string ERR_Email {
            get {
                return ResourceManager.GetString("ERR_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome e obrigatorio..
        /// </summary>
        public static string ERR_Name {
            get {
                return ResourceManager.GetString("ERR_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Senha e obrigatorio..
        /// </summary>
        public static string ERR_Password {
            get {
                return ResourceManager.GetString("ERR_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório.
        /// </summary>
        public static string ERR_RequiredField {
            get {
                return ResourceManager.GetString("ERR_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminino.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de Pagamento.
        /// </summary>
        public static string FormOfPayment {
            get {
                return ResourceManager.GetString("FormOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formas de Pagamento.
        /// </summary>
        public static string FormsPayment {
            get {
                return ResourceManager.GetString("FormsPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações de Grupo.
        /// </summary>
        public static string GroupSettings {
            get {
                return ResourceManager.GetString("GroupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Emissão.
        /// </summary>
        public static string IssuanceDate {
            get {
                return ResourceManager.GetString("IssuanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa Juridica.
        /// </summary>
        public static string LegalPerson {
            get {
                return ResourceManager.GetString("LegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de mensagem..
        /// </summary>
        public static string MSG_Type {
            get {
                return ResourceManager.GetString("MSG_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Compra.
        /// </summary>
        public static string NewBuy {
            get {
                return ResourceManager.GetString("NewBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Celular.
        /// </summary>
        public static string NewCellPhone {
            get {
                return ResourceManager.GetString("NewCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Cliente.
        /// </summary>
        public static string NewClient {
            get {
                return ResourceManager.GetString("NewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Email.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Funcionário.
        /// </summary>
        public static string NewEmployee {
            get {
                return ResourceManager.GetString("NewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Telefone.
        /// </summary>
        public static string NewPhone {
            get {
                return ResourceManager.GetString("NewPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Fornecedor.
        /// </summary>
        public static string NewProvider {
            get {
                return ResourceManager.GetString("NewProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Venda.
        /// </summary>
        public static string NewSale {
            get {
                return ResourceManager.GetString("NewSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operações.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        public static string Patio {
            get {
                return ResourceManager.GetString("Patio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condição de Pagamento.
        /// </summary>
        public static string PaymentTerms {
            get {
                return ResourceManager.GetString("PaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefones.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa Física.
        /// </summary>
        public static string PhysicalPerson {
            get {
                return ResourceManager.GetString("PhysicalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço custo.
        /// </summary>
        public static string PriceCost {
            get {
                return ResourceManager.GetString("PriceCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço venda.
        /// </summary>
        public static string PriceSale {
            get {
                return ResourceManager.GetString("PriceSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Fornecedor.
        /// </summary>
        public static string ProviderCode {
            get {
                return ResourceManager.GetString("ProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Fornecedor.
        /// </summary>
        public static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedores.
        /// </summary>
        public static string Providers {
            get {
                return ResourceManager.GetString("Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de parcelas.
        /// </summary>
        public static string QuantityOfParcels {
            get {
                return ResourceManager.GetString("QuantityOfParcels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebido.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Cadastro.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatorio.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processamento efetuado com sucesso..
        /// </summary>
        public static string ReturnSuccess {
            get {
                return ResourceManager.GetString("ReturnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        public static string RG {
            get {
                return ResourceManager.GetString("RG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venda.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Venda.
        /// </summary>
        public static string SaleCode {
            get {
                return ResourceManager.GetString("SaleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa de Compra.
        /// </summary>
        public static string SearchBuy {
            get {
                return ResourceManager.GetString("SearchBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa de Cliente.
        /// </summary>
        public static string SearchClient {
            get {
                return ResourceManager.GetString("SearchClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa de Funcionário.
        /// </summary>
        public static string SearchEmployee {
            get {
                return ResourceManager.GetString("SearchEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa de Venda.
        /// </summary>
        public static string SearchSale {
            get {
                return ResourceManager.GetString("SearchSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa de Fornecedor.
        /// </summary>
        public static string SearchSupplier {
            get {
                return ResourceManager.GetString("SearchSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o estado civil.
        /// </summary>
        public static string SelectMaritalStatus {
            get {
                return ResourceManager.GetString("SelectMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o estado.
        /// </summary>
        public static string SelectStates {
            get {
                return ResourceManager.GetString("SelectStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações de Usuarios.
        /// </summary>
        public static string SettingsForUsers {
            get {
                return ResourceManager.GetString("SettingsForUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estoque.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total Bruto.
        /// </summary>
        public static string TotalCrudeValue {
            get {
                return ResourceManager.GetString("TotalCrudeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total Desconto.
        /// </summary>
        public static string TotalValueDiscount {
            get {
                return ResourceManager.GetString("TotalValueDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total Liquido.
        /// </summary>
        public static string TotalValueLiquid {
            get {
                return ResourceManager.GetString("TotalValueLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de pessoa.
        /// </summary>
        public static string TypeOfPerson {
            get {
                return ResourceManager.GetString("TypeOfPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizações.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Bruto.
        /// </summary>
        public static string ValueCrude {
            get {
                return ResourceManager.GetString("ValueCrude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de Desconto.
        /// </summary>
        public static string ValueDiscount {
            get {
                return ResourceManager.GetString("ValueDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Documento.
        /// </summary>
        public static string ValueDocument {
            get {
                return ResourceManager.GetString("ValueDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Frete.
        /// </summary>
        public static string ValueFreight {
            get {
                return ResourceManager.GetString("ValueFreight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor líquido.
        /// </summary>
        public static string ValueLiquid {
            get {
                return ResourceManager.GetString("ValueLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
