//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoArtCouro.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Erros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Erros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoArtCouro.Resources.Resources.Erros", typeof(Erros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não informado.
        /// </summary>
        public static string ClientNotSet {
            get {
                return ResourceManager.GetString("ClientNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar senha e Senha não conferem.
        /// </summary>
        public static string ConfirmPasswordAndPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordAndPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível carregar as unidades..
        /// </summary>
        public static string CouldNotLoadUnits {
            get {
                return ResourceManager.GetString("CouldNotLoadUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome duplicado, já existe um grupo com esse nome.
        /// </summary>
        public static string DuplicateGruopName {
            get {
                return ResourceManager.GetString("DuplicateGruopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome duplicado, já existe um usuário com esse nome.
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço vazio.
        /// </summary>
        public static string EmptyAddress {
            get {
                return ResourceManager.GetString("EmptyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de permissão vazia.
        /// </summary>
        public static string EmptyAllowList {
            get {
                return ResourceManager.GetString("EmptyAllowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ vazio.
        /// </summary>
        public static string EmptyCNPJ {
            get {
                return ResourceManager.GetString("EmptyCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato vazio.
        /// </summary>
        public static string EmptyContact {
            get {
                return ResourceManager.GetString("EmptyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF vazio.
        /// </summary>
        public static string EmptyCPF {
            get {
                return ResourceManager.GetString("EmptyCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do grupo vazio.
        /// </summary>
        public static string EmptyGroupName {
            get {
                return ResourceManager.GetString("EmptyGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado civil vazio.
        /// </summary>
        public static string EmptyMaritalStatus {
            get {
                return ResourceManager.GetString("EmptyMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome vazio.
        /// </summary>
        public static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro {0} está vazio.
        /// </summary>
        public static string EmptyParameter {
            get {
                return ResourceManager.GetString("EmptyParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametros vazios.
        /// </summary>
        public static string EmptyParameters {
            get {
                return ResourceManager.GetString("EmptyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa vazia.
        /// </summary>
        public static string EmptyPerson {
            get {
                return ResourceManager.GetString("EmptyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone vazio.
        /// </summary>
        public static string EmptyPhone {
            get {
                return ResourceManager.GetString("EmptyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG vazio.
        /// </summary>
        public static string EmptyRG {
            get {
                return ResourceManager.GetString("EmptyRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo vazio.
        /// </summary>
        public static string EmptySex {
            get {
                return ResourceManager.GetString("EmptySex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao carregar permissões.
        /// </summary>
        public static string FailedToLoadPermissions {
            get {
                return ResourceManager.GetString("FailedToLoadPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao atualizar permissoes do usuario logado..
        /// </summary>
        public static string FailuretoUpdatePermissionsUserOnline {
            get {
                return ResourceManager.GetString("FailuretoUpdatePermissionsUserOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de pagamento não existe.
        /// </summary>
        public static string FormOfPaymentDoesNotExist {
            get {
                return ResourceManager.GetString("FormOfPaymentDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo não existe.
        /// </summary>
        public static string GroupDoesNotExist {
            get {
                return ResourceManager.GetString("GroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido.
        /// </summary>
        public static string InvalidCNPJ {
            get {
                return ResourceManager.GetString("InvalidCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código inválido.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido.
        /// </summary>
        public static string InvalidCPF {
            get {
                return ResourceManager.GetString("InvalidCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credencial inválida.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetro {0} inválido.
        /// </summary>
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de parcelas deve ser 0 a 99.
        /// </summary>
        public static string InvalidQuantityOfParcels {
            get {
                return ResourceManager.GetString("InvalidQuantityOfParcels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do usuário inválido.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome ou senhas estão incorretos.
        /// </summary>
        public static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida.
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meio de comunicação vazio.
        /// </summary>
        public static string MeansOfCommunicationEmpty {
            get {
                return ResourceManager.GetString("MeansOfCommunicationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há conta a receber para o filtro informado.
        /// </summary>
        public static string NoAccountReceivableForTheGivenFilter {
            get {
                return ResourceManager.GetString("NoAccountReceivableForTheGivenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há clientes para o filtro informado.
        /// </summary>
        public static string NoClientForTheGivenFilter {
            get {
                return ResourceManager.GetString("NoClientForTheGivenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há funcionário para o filtro informado.
        /// </summary>
        public static string NoEmployeeForTheGivenFilter {
            get {
                return ResourceManager.GetString("NoEmployeeForTheGivenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há grupo para o filtro informado.
        /// </summary>
        public static string NoGruopForTheGivenFilter {
            get {
                return ResourceManager.GetString("NoGruopForTheGivenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há fornecedor para o filtro informado.
        /// </summary>
        public static string NoProviderForTheGivenFilter {
            get {
                return ResourceManager.GetString("NoProviderForTheGivenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há vendas para o filtro informado.
        /// </summary>
        public static string NoSaleForTheGivenFilter {
            get {
                return ResourceManager.GetString("NoSaleForTheGivenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há compras para o filtro informado.
        /// </summary>
        public static string NoShoppingForTheGivenFilter {
            get {
                return ResourceManager.GetString("NoShoppingForTheGivenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de pagamento não informado.
        /// </summary>
        public static string NotSetPayment {
            get {
                return ResourceManager.GetString("NotSetPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro {0} não pode ser zero.
        /// </summary>
        public static string NotZeroParameter {
            get {
                return ResourceManager.GetString("NotZeroParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há usuarios para o filtro informado.
        /// </summary>
        public static string NoUsersForTheGivenFilter {
            get {
                return ResourceManager.GetString("NoUsersForTheGivenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro {0} está nulo.
        /// </summary>
        public static string NullParameter {
            get {
                return ResourceManager.GetString("NullParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papel pessoa vazio.
        /// </summary>
        public static string PaperEmptyPerson {
            get {
                return ResourceManager.GetString("PaperEmptyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condição de pagamento não existe.
        /// </summary>
        public static string PaymentConditionDoesNotExist {
            get {
                return ResourceManager.GetString("PaymentConditionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condição de pagamento não informado.
        /// </summary>
        public static string PaymentConditionNotSet {
            get {
                return ResourceManager.GetString("PaymentConditionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissões não cadastradas.
        /// </summary>
        public static string PermissionsNotRegistered {
            get {
                return ResourceManager.GetString("PermissionsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa não existe.
        /// </summary>
        public static string PersonDoesNotExist {
            get {
                return ResourceManager.GetString("PersonDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto não existe.
        /// </summary>
        public static string ProductDoesNotExist {
            get {
                return ResourceManager.GetString("ProductDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto: {0}, Quantidade informada: {1}, Quantidade em estoque: {2}.
        /// </summary>
        public static string ProductInsufficient {
            get {
                return ResourceManager.GetString("ProductInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto(s) que falta(m) no estoque.
        /// </summary>
        public static string ProductsThatAreMissingInStock {
            get {
                return ResourceManager.GetString("ProductsThatAreMissingInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor não informado.
        /// </summary>
        public static string ProviderNotSet {
            get {
                return ResourceManager.GetString("ProviderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra confirmada não pode ser excluída.
        /// </summary>
        public static string PurchaseConfirmedCanNotBeExcluded {
            get {
                return ResourceManager.GetString("PurchaseConfirmedCanNotBeExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra não existe.
        /// </summary>
        public static string PurchaseDoesNotExist {
            get {
                return ResourceManager.GetString("PurchaseDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra não informada.
        /// </summary>
        public static string PurchaseNotSet {
            get {
                return ResourceManager.GetString("PurchaseNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Obrigatório.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venda confirmada não pode ser excluida..
        /// </summary>
        public static string SaleConfirmedCanNotBeExcluded {
            get {
                return ResourceManager.GetString("SaleConfirmedCanNotBeExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venda não existe.
        /// </summary>
        public static string SaleDoesNotExist {
            get {
                return ResourceManager.GetString("SaleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens da venda não informado.
        /// </summary>
        public static string SaleItemsNotSet {
            get {
                return ResourceManager.GetString("SaleItemsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venda não informada.
        /// </summary>
        public static string SaleNotSet {
            get {
                return ResourceManager.GetString("SaleNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venda não informada.
        /// </summary>
        public static string SaleUnknown {
            get {
                return ResourceManager.GetString("SaleUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da compra diferente de aberto.
        /// </summary>
        public static string StatusOfDifferentPurchasingOpen {
            get {
                return ResourceManager.GetString("StatusOfDifferentPurchasingOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da venda diferente de aberto.
        /// </summary>
        public static string StatusOfDifferentSalesOpen {
            get {
                return ResourceManager.GetString("StatusOfDifferentSalesOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soma do valores não conferem com o Valor Total Bruto.
        /// </summary>
        public static string SumDoNotMatchTotalCrudeValue {
            get {
                return ResourceManager.GetString("SumDoNotMatchTotalCrudeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soma do valores não conferem com o Valor Total Desconto.
        /// </summary>
        public static string SumDoNotMatchTotalValueDiscount {
            get {
                return ResourceManager.GetString("SumDoNotMatchTotalValueDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soma do valores não conferem com o Valor Total Líquido.
        /// </summary>
        public static string SumDoNotMatchTotalValueLiquid {
            get {
                return ResourceManager.GetString("SumDoNotMatchTotalValueLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soma do valores não conferem com o Valor Total Frete.
        /// </summary>
        public static string SumDoNotMatchTotalValueShipping {
            get {
                return ResourceManager.GetString("SumDoNotMatchTotalValueShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe conta a pagar com código igual a zero.
        /// </summary>
        public static string ThereAccountPayableWithCodeZero {
            get {
                return ResourceManager.GetString("ThereAccountPayableWithCodeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe conta a receber com código igual a zero.
        /// </summary>
        public static string ThereReceivableWithZeroCode {
            get {
                return ResourceManager.GetString("ThereReceivableWithZeroCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não autorizado..
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade não existe.
        /// </summary>
        public static string UnitDoesNotExist {
            get {
                return ResourceManager.GetString("UnitDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não existe.
        /// </summary>
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não informado.
        /// </summary>
        public static string UserNotSet {
            get {
                return ResourceManager.GetString("UserNotSet", resourceCulture);
            }
        }
    }
}
